<script setup lang="ts">
  import { onMounted, ref, computed } from 'vue';
  import DataStatusBuilder from '@/shared/DataStatues/DataStatusBuilder.vue';
  import AppTable, { type TableHeader } from '@/shared/HelpersComponents/AppTable.vue';
  import Pagination from '@/shared/HelpersComponents/Pagination.vue';
  import { useRoute, useRouter } from 'vue-router';
  import { debounce } from '@/base/Presentation/Utils/debouced';
  import DeleteDialog from '@/shared/HelpersComponents/dialog/DeleteDialog.vue';
  import { useFormsStore } from '@/stores/formsStore';
  import IndexPluseIcon from '@/shared/icons/IndexPluseIcon.vue';
  import IndexSearchIcon from '@/shared/icons/IndexSearchIcon.vue';
  import FilterDialog from '@/shared/HelpersComponents/FilterDialog/FilterDialog.vue';
  import TableSkelaton from '@/shared/HelpersComponents/TableSkelaton.vue';
  import { QuestionGeneratedByEnum } from '../../core/constant/generatedby.enum';
  import { QuestionTypeEnum } from '../../core/constant/question.type.enum';
  import { QuestionStatusEnum } from '../../core/constant/question.status.enum';
  import ShowIcon from '@/shared/icons/ShowIcon.vue';
  import ArticleController from '../controllers/Article.controller';
  import IndexArticleParams from '../../core/params/index.Articles.params';
  import DeleteArticleParams from '../../core/params/Articles.question.params';
  import type ShowArticleModel from '../../core/models/show.Article.model';
  import Articlearrow from '@/shared/icons/articlearrow.vue';
  import Articlesubject from '@/shared/icons/articlesubject.vue';

  // Controller instance
  const controller = ArticleController.getInstance();
  const state = computed(() => controller.listState.value);
  const router = useRouter();
  const route = useRoute();

  const FormStore = useFormsStore();
  const formRoute = computed(() => `/${route.params.country_code}/articles/add`);

  // Table headers
  const headers: TableHeader[] = [
    { key: 'id', label: 'ID', width: '10%', sortable: true },
    { key: 'articleTitle', label: 'article title', width: '30%' },
    { key: 'subject', label: 'subject', width: '15%' },
    { key: 'generatedBy', label: 'generated by', width: '15%' },
    { key: 'noOfQs', label: 'No of Qs', width: '15%' },
  ];

  // Pagination state
  const perPage = ref(10);
  const word = ref('');

  const fetchArticles = async (page: number = 1, wordStr: string = '') => {
    await controller.fetchList(
      new IndexArticleParams({
        word: wordStr || word.value,
        pageNumber: page,
        perPage: perPage.value,
        withPage: 1,
      }),
    );
  };

  const Search = debounce(() => {
    router.push({
      query: {
        ...route.query,
        page: 1,
        word: word.value || undefined,
      },
    });
    fetchArticles(1, word.value);
  });

  const onPageChange = (page: number) => {
    fetchArticles(page);
    router.push({
      query: {
        ...route.query,
        page: String(page),
        word: word.value,
      },
    });
  };

  const onPerPageChange = (count: number) => {
    perPage.value = count;
    fetchArticles(1);
  };

  onMounted(async () => {
    if (route.query.word) {
      word.value = String(route.query.word);
    }
    await fetchArticles(route.query.page ? Number(route.query.page) : 1, word.value);
  });

  const deleteArticle = async (id: number) => {
    await controller.delete(new DeleteArticleParams(id));
    await fetchArticles();
  };

  const isDraft = computed(() => {
    const data = FormStore?.formData[formRoute.value] ?? {};
    return Object.keys(data).length === 0 || Object.values(data).every((v) => v == null);
  });

  const FilterDialogShow = ref<boolean>(false);
  const ApplayFilter = () => {
    FilterDialogShow.value = false;
  };
  const CloseFiletrDialog = () => {
    FilterDialogShow.value = false;
  };

  const GetGneratedBy = (val: QuestionGeneratedByEnum) => {
    switch (val) {
      case QuestionGeneratedByEnum.manual:
        return 'Manual';
      case QuestionGeneratedByEnum.ai:
        return 'AI';
    }
  };

  const GetQusetionType = (val: QuestionTypeEnum) => {
    switch (val) {
      case QuestionTypeEnum.mcq:
        return 'MCQ';
      case QuestionTypeEnum.complate:
        return 'Complete';
      case QuestionTypeEnum.true_false:
        return 'True/False';
      case QuestionTypeEnum.ranking:
        return 'Ranking';
      case QuestionTypeEnum.matching:
        return 'Matching';
    }
  };

  const GetQuestionStatus = (val: QuestionStatusEnum) => {
    switch (val) {
      case QuestionStatusEnum.approved:
        return 'Approved';
      case QuestionStatusEnum.not_Reviewd:
        return 'Not Reviewed';
      case QuestionStatusEnum.rejected:
        return 'Rejected';
      case QuestionStatusEnum.under_review:
        return 'Under Review';
    }
  };
</script>

<template>
  <!-- <MultiSelectionTabs /> -->
  <div class="artical-page">
    <div class="index-header">
      <div class="search-field">
        <span class="search-icon">
          <IndexSearchIcon />
        </span>
        <input
          v-model="word"
          placeholder="Search by employee name or email…"
          class="search-input"
          type="text"
          @input="Search"
        />
      </div>
      <div class="btns-container">
        <!-- <button class="btn btn-secondary" @click="exportExcel">
          <ExportExcelIcon />
          <span>{{ $t('export') }}</span>
        </button> -->
        <router-link :to="formRoute" class="btn btn-primary btn-add">
          <IndexPluseIcon />
          <span>{{ isDraft ? 'new artical' : 'continue adding' }}</span>
        </router-link>
        <FilterDialog v-model="FilterDialogShow">
          <template #content>
            <div class="filter-action">
              <button class="btn btn-cancel" @click="CloseFiletrDialog">Reset</button>
              <button class="btn btn-primary" @click="ApplayFilter">apply</button>
            </div>
          </template>
        </FilterDialog>
      </div>
    </div>

    <DataStatusBuilder :controller="state" :on-retry="async () => await fetchArticles()">
      <template #success="{ data }">
        <div class="table-frame">
          <AppTable
            :headers="headers"
            :items="data as ShowArticleModel[]"
            :hoverable="true"
            :striped="true"
            show-index
          >
            <template #cell-articleType="{ item }">
              <div class="question-type">
                {{ GetQusetionType(item.articleType!) }}
              </div>
            </template>
            <template #cell-subject="{ item }">
              <div class="subject-cell">
                <span class="subject-curriculum">
                  {{ item.subject?.curriculum }}
                  <Articlearrow class="arrow-icon" />
                </span>
                <span class="subject-cycle">
                  {{ item.subject?.cycle }}
                  <Articlesubject />
                  <span class="subject-lang">{{ item.subject?.language ?? 'Arabic' }}</span>
                </span>

                <span class="subject-grade">
                  <Articlearrow class="arrow-icon" />
                  {{ item.subject?.grade }}
                </span>
              </div>
            </template>
            <template #cell-status="{ item }">
              <div
                class="status"
                :class="{
                  'status-approved': item.status === QuestionStatusEnum.approved,
                  'status-not-reviewed': item.status === QuestionStatusEnum.not_Reviewd,
                  'status-rejected': item.status === QuestionStatusEnum.rejected,
                  'status-under-review': item.status === QuestionStatusEnum.under_review,
                }"
              >
                {{ GetQuestionStatus(item.status!) }}
              </div>
            </template>
            <template #cell-generatedBy="{ item }">
              <div class="generatedBy">
                {{ GetGneratedBy(item.generatedBy!) }}
              </div>
            </template>

            <template #actions="{ item }">
              <div class="row-actions">
                <router-link
                  class="action-btn edit"
                  :to="`/${route.params.country_code}/articles/edit/${item.id}`"
                  title="Edit"
                >
                  <svg
                    width="15"
                    height="15"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                  </svg>
                </router-link>
                <router-link
                  :to="`/${route.params.country_code}/articles/edit/${item.id}`"
                  title="show"
                  class="action-btn show"
                >
                  <ShowIcon />
                </router-link>

                <DeleteDialog @delete="deleteArticle(item.id!)">
                  <template #Dialog>
                    <button class="action-btn delete" title="Delete">
                      <svg
                        width="15"
                        height="15"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path d="M3 6h18" />
                        <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
                        <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
                      </svg>
                    </button>
                  </template>
                </DeleteDialog>
              </div>
            </template>
          </AppTable>
        </div>

        <Pagination
          v-if="controller.pagination.value"
          :pagination="controller.pagination.value"
          @change-page="onPageChange"
          @count-per-page="onPerPageChange"
        />
      </template>

      <template #loader>
        <TableSkelaton
          :rows="5"
          :columns="headers.length"
          :has-actions="true"
          :show-index="true"
          :selectable="true"
        >
        </TableSkelaton>
      </template>
    </DataStatusBuilder>
  </div>
</template>

<style scoped lang="scss">
  .subject-cell {
    display: flex;
    flex-direction: column;
    gap: 3px;
    font-size: 13px;
    line-height: 1.5;

    .subject-curriculum {
      color: var(--gray-5, #888);
      font-size: 12px;
      position: relative;

      .arrow-icon {
        position: absolute;
        left: -20px;
        top: 100%;
        transform: translateY(-50%);
      }
    }

    .subject-cycle {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 5px;
      font-weight: 500;
      color: var(--color-text-primary);

      .subject-lang {
        color: var(--PrimaryColor, #1d9e75);
        font-weight: 500;
      }
    }

    .subject-grade {
      display: flex;
      align-items: center;
      gap: 4px;
      color: var(--gray-5, #888);
      font-size: 12px;
      position: relative;

      .arrow-icon {
        position: absolute;
        left: -20px;
        top: 20%;
        transform: translateY(-50%);
      }
    }
  }
</style>
