<script setup lang="ts">
import { onMounted, ref, computed } from 'vue';
import DataStatusBuilder from '@/shared/DataStatues/DataStatusBuilder.vue';
import AppTable, { type TableHeader } from '@/shared/HelpersComponents/AppTable.vue';
import Pagination from '@/shared/HelpersComponents/Pagination.vue';
import { useRoute, useRouter } from 'vue-router';
import { debounce } from '@/base/Presentation/Utils/debouced';
import DeleteDialog from '@/shared/HelpersComponents/dialog/DeleteDialog.vue';
import { useFormsStore } from '@/stores/formsStore';
import IndexPluseIcon from '@/shared/icons/IndexPluseIcon.vue';
import IndexSearchIcon from '@/shared/icons/IndexSearchIcon.vue';
import FilterDialog from '@/shared/HelpersComponents/FilterDialog/FilterDialog.vue';
import TableSkelaton from '@/shared/HelpersComponents/TableSkelaton.vue';
import { ArticleGeneratedByEnum } from '../../core/constant/Article.generatedby.enum';
import { ArticleTypeEnum } from '../../core/constant/Article.type.enum';
import { ArticleStatusEnum } from '../../core/constant/Article.status.enum';
import ShowIcon from '@/shared/icons/ShowIcon.vue';
import ArticleController from '../controllers/Article.controller';
import IndexArticleParams from '../../core/params/index.Articles.params';
import DeleteArticleParams from '../../core/params/delet.Articles.params';
// import type ShowArticleModel from '../../core/models/show.Article.model';
import Articlearrow from '@/shared/icons/articlearrow.vue';
import Articlesubject from '@/shared/icons/articlesubject.vue';
import type ArticleModel from '../../core/models/Article.model';
import type ArticleSubjectModel from '../../core/models/Subject.model';

// Controller instance
const controller = ArticleController.getInstance();
const state = computed(() => controller.listState.value);
const router = useRouter();
const route = useRoute();

const FormStore = useFormsStore();
const formRoute = computed(() => '/articles/add');

// Table headers
const headers: TableHeader[] = [
  { key: 'id', label: 'ID', width: '10%', sortable: true },
  { key: 'articleTitle', label: 'article title', width: '30%' },
  { key: 'subject', label: 'subject', width: '15%' },
  { key: 'generatedBy', label: 'generated by', width: '15%' },
  { key: 'noOfQs', label: 'No of Qs', width: '15%' },
];

// Pagination state
const perPage = ref(10);
const word = ref('');

// const fetchArticles = async (page: number = 1, wordStr: string = '') => {
//   await controller.fetchList(
//     new IndexArticleParams({
//       word: wordStr || word.value,
//       pageNumber: page,
//       perPage: perPage.value,
//       withPage: 1,
//     }),
//   );
// };

const fetchArticles = async (page: number = 1, wordStr: string = '') => {
  await controller.fetchList(
    new IndexArticleParams({
      word: wordStr || word.value,
      pageNumber: page,
      perPage: perPage.value,
      withPage: 1,
      // question_type: ArticleQuestionTypeEnum.PARAGRAPH,
    }),
  );
};

// const Search = debounce(() => {
//   router.push({
//     query: {
//       ...route.query,
//       page: 1,
//       word: word.value || undefined,
//     },
//   });
const Search = debounce(() => {
  router.push({
    query: {
      ...route.query,
      page: 1,
      word: word.value || undefined,
    },
  });

  fetchArticles(1);
});

const onPageChange = (page: number) => {
  fetchArticles(page);
  router.push({
    query: {
      ...route.query,
      page: String(page),
      word: word.value,
    },
  });
};

const onPerPageChange = (count: number) => {
  perPage.value = count;
  fetchArticles(1);
};

onMounted(async () => {
  if (route.query.word) {
    word.value = String(route.query.word);
  }
  await fetchArticles(route.query.page ? Number(route.query.page) : 1, word.value);
});

const deleteArticle = async (id: number) => {
  await controller.delete(new DeleteArticleParams(id));
  await fetchArticles();
};

const isDraft = computed(() => {
  const data = FormStore?.formData[formRoute.value] ?? {};
  return Object.keys(data).length === 0 || Object.values(data).every((v) => v == null);
});

const FilterDialogShow = ref<boolean>(false);
const ApplayFilter = () => {
  FilterDialogShow.value = false;
};
const CloseFiletrDialog = () => {
  FilterDialogShow.value = false;
};

const GetGneratedBy = (val: ArticleGeneratedByEnum) => {
  switch (val) {
    case ArticleGeneratedByEnum.manual:
      return 'Manual';
    case ArticleGeneratedByEnum.ai:
      return 'AI';
    default:
      return 'N/A';
  }
};

const GetQusetionType = (val: ArticleTypeEnum) => {
  switch (val) {
    case ArticleTypeEnum.mcq:
      return 'MCQ';
    case ArticleTypeEnum.complate:
      return 'Complete';
    case ArticleTypeEnum.true_false:
      return 'True/False';
    case ArticleTypeEnum.ranking:
      return 'Ranking';
    case ArticleTypeEnum.matching:
      return 'Matching';
  }
};

const GetQuestionStatus = (val: ArticleStatusEnum) => {
  switch (val) {
    case ArticleStatusEnum.approved:
      return 'Approved';
    case ArticleStatusEnum.not_Reviewd:
      return 'Not Reviewed';
    case ArticleStatusEnum.rejected:
      return 'Rejected';
    case ArticleStatusEnum.under_review:
      return 'Under Review';
  }
};

// delet arrow from article subject and show only title 
const deleteArrow = (subject: ArticleSubjectModel) => {
  const subjects = subject?.full_title?.split(/\s*->\s*/g);
  return subjects?.map((subject) => subject.trim());
}
</script>

<template>
  <!-- <MultiSelectionTabs /> -->
  <div class="artical-page">
    <div class="index-header">
      <div class="search-field">
        <span class="search-icon">
          <IndexSearchIcon />
        </span>
        <input v-model="word" placeholder="Search by employee name or email…" class="search-input" type="text"
          @input="Search" />
      </div>
      <div class="btns-container">
        <!-- <button class="btn btn-secondary" @click="exportExcel">
          <ExportExcelIcon />
          <span>{{ $t('export') }}</span>
        </button> -->
        <router-link :to="formRoute" class="btn btn-primary btn-add">
          <IndexPluseIcon />
          <span>{{ isDraft ? 'new artical' : 'continue adding' }}</span>
        </router-link>
        <FilterDialog v-model="FilterDialogShow">
          <template #content>
            <div class="filter-action">
              <button class="btn btn-cancel" @click="CloseFiletrDialog">Reset</button>
              <button class="btn btn-primary" @click="ApplayFilter">apply</button>
            </div>
          </template>
        </FilterDialog>
      </div>
    </div>

    <DataStatusBuilder :controller="state" :on-retry="async () => await fetchArticles()">
      <template #success="{ data }">
        <div class="table-frame">
          <AppTable :headers="headers" :items="data as ArticleModel[]" :hoverable="true" :striped="true" show-index>
            <template #cell-articleType="{ item }">
              <div class="question-type">
                {{ GetQusetionType(item.articleType!) }}
              </div>
            </template>
            <template #cell-subject="{ item }">
              <div class="subject-cell">


                <div class="parent-subject-curriculum">
                  <span v-for="(subject, index) in deleteArrow(item?.subject)" :key="index" class="subject-curriculum">
                    <p> {{ subject }}</p>
                    <Articlearrow v-if="index < deleteArrow(item?.subject).length - 1" class="arrow-icon" />
                  </span>
                </div>
                <div>
                  <Articlesubject />
                </div>
                <span class="subject-cycle">
                  <span class="subject-lang">{{ item.e_c_subject?.title }}</span>
                </span>
              </div>
            </template>
            <template #cell-status="{ item }">
              <div class="status" :class="{
                'status-approved': item.status === ArticleStatusEnum.approved,
                'status-not-reviewed': item.status === ArticleStatusEnum.not_Reviewd,
                'status-rejected': item.status === ArticleStatusEnum.rejected,
                'status-under-review': item.status === ArticleStatusEnum.under_review,
              }">
                {{ GetQuestionStatus(item.status!) }}
              </div>
            </template>
            <template #cell-generatedBy="{ item }">
              <div class="generatedBy">
                {{ GetGneratedBy(item.generatedBy!) }}
              </div>
            </template>

            <template #actions="{ item }">
              <div class="row-actions">
                <router-link class="action-btn edit" :to="`/articles/edit/${item.id}`" title="Edit">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                    stroke-linecap="round" stroke-linejoin="round">
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                  </svg>
                </router-link>
                <router-link :to="`/articles/show/${item.id}`" title="show" class="action-btn show">
                  <ShowIcon />
                </router-link>

                <DeleteDialog @delete="deleteArticle(item.id!)">
                  <template #Dialog>
                    <button class="action-btn delete" title="Delete">
                      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                        stroke-linecap="round" stroke-linejoin="round">
                        <path d="M3 6h18" />
                        <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
                        <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
                      </svg>
                    </button>
                  </template>
                </DeleteDialog>
              </div>
            </template>
          </AppTable>
        </div>

        <Pagination v-if="controller.pagination.value" :pagination="controller.pagination.value"
          @change-page="onPageChange" @count-per-page="onPerPageChange" />
      </template>

      <template #loader>
        <TableSkelaton :rows="5" :columns="headers.length" :has-actions="true" :show-index="true" :selectable="true">
        </TableSkelaton>
      </template>
    </DataStatusBuilder>
  </div>
</template>