<script setup lang="ts">
  import { onMounted, ref, computed } from 'vue';
  import DataStatusBuilder from '@/shared/DataStatues/DataStatusBuilder.vue';
  import AppTable, { type TableHeader } from '@/shared/HelpersComponents/AppTable.vue';
  import Pagination from '@/shared/HelpersComponents/Pagination.vue';
  import { useRoute, useRouter } from 'vue-router';
  import { debounce } from '@/base/Presentation/Utils/debouced';
  import DeleteEmployeeParams from '../../core/params/delete.question.params';
  import DeleteDialog from '@/shared/HelpersComponents/dialog/DeleteDialog.vue';
  import { useFormsStore } from '@/stores/formsStore';
  import IndexPluseIcon from '@/shared/icons/IndexPluseIcon.vue';
  // import ExportExcelIcon from '@/shared/icons/ExportExcelIcon.vue';
  import IndexSearchIcon from '@/shared/icons/IndexSearchIcon.vue';
  import FilterDialog from '@/shared/HelpersComponents/FilterDialog/FilterDialog.vue';
  import TableSkelaton from '@/shared/HelpersComponents/TableSkelaton.vue';
  // import MultiSelectionTabs from '../subComponents/MultiSelectionTabs.vue';
  import questionsController from '../controllers/questions.controller';
  import { QuestionGeneratedByEnum } from '../../core/constant/generatedby.enum';
  import { QuestionTypeEnum } from '../../core/constant/question.type.enum';
  import { QuestionDifficultyEnum } from '../../core/constant/question.difficulty.enum';
  import { QuestionStatusEnum } from '../../core/constant/question.status.enum';
  import type questionsModel from '../../core/models/questions.model';
  import IndexQuestionsParams from '../../core/params/index.question.params';

  // Controller instance
  const controller = questionsController.getInstance();
  const state = computed(() => controller.listState.value);
  const router = useRouter();
  const route = useRoute();

  const FormStore = useFormsStore();
  const formRoute = computed(() => `/${route.params.country_code}/questions/add`);

  // Table headers
  const headers: TableHeader[] = [
    { key: 'id', label: 'ID', width: '10%', sortable: true },
    { key: 'title', label: 'Question', width: '30%' },
    { key: 'generatedBy', label: 'Generated By', width: '15%' },
    { key: 'questionType', label: 'Type', width: '15%' },
    { key: 'difficulty', label: 'Difficulty', width: '15%' },
    { key: 'status', label: 'Status', width: '15%' },
  ];

  // Pagination state
  const perPage = ref(10);
  const word = ref('');

  const fetchQuestions = async (page: number = 1, wordStr: string = '') => {
    await controller.fetchList(
      new IndexQuestionsParams({
        word: wordStr || word.value,
        pageNumber: page,
        perPage: perPage.value,
        withPage: 1,
      }),
    );
  };

  const Search = debounce(() => {
    router.push({
      query: {
        ...route.query,
        page: 1,
        word: word.value || undefined,
      },
    });
    fetchQuestions(1, word.value);
  });

  const onPageChange = (page: number) => {
    fetchQuestions(page);
    router.push({
      query: {
        ...route.query,
        page: String(page),
        word: word.value,
      },
    });
  };

  const onPerPageChange = (count: number) => {
    perPage.value = count;
    fetchQuestions(1);
  };

  onMounted(async () => {
    if (route.query.word) {
      word.value = String(route.query.word);
    }
    await fetchQuestions(route.query.page ? Number(route.query.page) : 1, word.value);
  });

  const deleteEmployee = async (id: number) => {
    await controller.delete(new DeleteEmployeeParams(id));
    await fetchQuestions();
  };

  const isDraft = computed(() => {
    const data = FormStore?.formData[formRoute.value] ?? {};
    return Object.keys(data).length === 0 || Object.values(data).every((v) => v == null);
  });

  const FilterDialogShow = ref<boolean>(false);
  const ApplayFilter = () => {
    FilterDialogShow.value = false;
  };
  const CloseFiletrDialog = () => {
    FilterDialogShow.value = false;
  };

  const GetGneratedBy = (val: QuestionGeneratedByEnum) => {
    switch (val) {
      case QuestionGeneratedByEnum.manual:
        return 'Manual';
      case QuestionGeneratedByEnum.ai:
        return 'AI';
    }
  };

  const GetQusetionType = (val: QuestionTypeEnum) => {
    switch (val) {
      case QuestionTypeEnum.mcq:
        return 'MCQ';
      case QuestionTypeEnum.complate:
        return 'Complete';
      case QuestionTypeEnum.true_false:
        return 'True/False';
      case QuestionTypeEnum.ranking:
        return 'Ranking';
      case QuestionTypeEnum.matching:
        return 'Matching';
    }
  };

  const GetDifficulty = (val: QuestionDifficultyEnum) => {
    switch (val) {
      case QuestionDifficultyEnum.easy:
        return 'Easy';
      case QuestionDifficultyEnum.medium:
        return 'Medium';
      case QuestionDifficultyEnum.hard:
        return 'Hard';
    }
  };

  const GetQuestionStatus = (val: QuestionStatusEnum) => {
    switch (val) {
      case QuestionStatusEnum.approved:
        return 'Approved';
      case QuestionStatusEnum.not_Reviewd:
        return 'Not Reviewed';
      case QuestionStatusEnum.rejected:
        return 'Rejected';
      case QuestionStatusEnum.under_review:
        return 'Under Review';
    }
  };
</script>

<template>
  <!-- <MultiSelectionTabs /> -->
  <div class="questions-page">
    <div class="index-header">
      <div class="search-field">
        <span class="search-icon">
          <IndexSearchIcon />
        </span>
        <input
          v-model="word"
          placeholder="Search by employee name or email…"
          class="search-input"
          type="text"
          @input="Search"
        />
      </div>
      <div class="btns-container">
        <!-- <button class="btn btn-secondary" @click="exportExcel">
          <ExportExcelIcon />
          <span>{{ $t('export') }}</span>
        </button> -->
        <router-link :to="formRoute" class="btn btn-primary btn-add">
          <IndexPluseIcon />
          <span>{{ isDraft ? 'Add Questions' : 'Continue Adding' }}</span>
        </router-link>
        <FilterDialog v-model="FilterDialogShow">
          <template #content>
            <div class="filter-action">
              <button class="btn btn-cancel" @click="CloseFiletrDialog">Reset</button>
              <button class="btn btn-primary" @click="ApplayFilter">apply</button>
            </div>
          </template>
        </FilterDialog>
      </div>
    </div>

    <DataStatusBuilder :controller="state" :on-retry="async () => await fetchQuestions()">
      <template #success="{ data }">
        <div class="table-frame">
          <AppTable
            :headers="headers"
            :items="data as questionsModel[]"
            :hoverable="true"
            :striped="true"
            show-index
          >
            <template #cell-questionType="{ item }">
              <div class="question-type">
                {{ GetQusetionType(item.questionType) }}
              </div>
            </template>
            <template #cell-difficulty="{ item }">
              <div class="difficulty">
                {{ GetDifficulty(item.difficulty) }}
              </div>
            </template>
            <template #cell-status="{ item }">
              <div
                class="status"
                :class="{
                  'status-approved': item.status === QuestionStatusEnum.approved,
                  'status-not-reviewed': item.status === QuestionStatusEnum.not_Reviewd,
                  'status-rejected': item.status === QuestionStatusEnum.rejected,
                  'status-under-review': item.status === QuestionStatusEnum.under_review,
                }"
              >
                {{ GetQuestionStatus(item.status) }}
              </div>
            </template>
            <template #cell-generatedBy="{ item }">
              <div class="generatedBy">
                {{ GetGneratedBy(item.generatedBy) }}
              </div>
            </template>

            <template #actions="{ item }">
              <div class="row-actions">
                <router-link
                  class="action-btn edit"
                  :to="`/${route.params.country_code}/employees/edit/${item.id}`"
                  title="Edit"
                >
                  <svg
                    width="15"
                    height="15"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                  </svg>
                </router-link>

                <DeleteDialog @delete="deleteEmployee(item.id!)">
                  <template #Dialog>
                    <button class="action-btn delete" title="Delete">
                      <svg
                        width="15"
                        height="15"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path d="M3 6h18" />
                        <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
                        <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
                      </svg>
                    </button>
                  </template>
                </DeleteDialog>
              </div>
            </template>
          </AppTable>
        </div>

        <Pagination
          v-if="controller.pagination.value"
          :pagination="controller.pagination.value"
          @change-page="onPageChange"
          @count-per-page="onPerPageChange"
        />
      </template>

      <template #loader>
        <TableSkelaton
          :rows="5"
          :columns="headers.length"
          :has-actions="true"
          :show-index="true"
          :selectable="true"
        >
        </TableSkelaton>
      </template>
    </DataStatusBuilder>
  </div>
</template>
