<script setup lang="ts">
  import { QuestionGeneratedByEnum } from '@/modules/Questions/core/constant/generatedby.enum';
  import { QuestionStatusEnum } from '@/modules/Questions/core/constant/question.status.enum';
  import type ShowQuestionsModel from '@/modules/Questions/core/models/show.questions.model';
  import { computed } from 'vue';

  const { questionData } = defineProps<{ questionData: ShowQuestionsModel }>();

  const statusClasses = computed(() => {
    if (!questionData?.review_status) return '';
    const status = questionData.review_status;

    return {
      waiting: status == QuestionStatusEnum.PENDING,
      drafting: status == QuestionStatusEnum.PENDING,
      rejected: status == QuestionStatusEnum.REJECTED,
      approved: status == QuestionStatusEnum.APPROVED,
    };
  });

  const getStatusLabel = (review_status: QuestionStatusEnum) => {
    switch (review_status) {
      case QuestionStatusEnum.PENDING:
        return 'Under Review';
      case QuestionStatusEnum.REJECTED:
        return 'Rejected';
      case QuestionStatusEnum.APPROVED:
        return 'Approved';
      default:
        return review_status;
    }
  };

  const getGeneratedByLabel = (from_source_type: QuestionGeneratedByEnum) => {
    switch (from_source_type) {
      case QuestionGeneratedByEnum.manual:
        return 'Manual';
      case QuestionGeneratedByEnum.ai:
        return 'AI';
      default:
        return from_source_type;
    }
  };
</script>

<template>
  <div class="question-status-card" :class="statusClasses">
    <div class="status-grid">
      <div class="status-item">
        <label>Status</label>
        <h3>{{ getStatusLabel(questionData?.review_status!) }}</h3>
      </div>

      <div class="status-item">
        <label>Question Id</label>
        <h3>{{ questionData?.question_id }}</h3>
      </div>

      <div class="status-item">
        <label>Generated By</label>
        <h3>{{ getGeneratedByLabel(questionData.from_source_type!) }}</h3>
      </div>

      <div class="status-item">
        <label>Created At</label>
        <h3>{{ questionData?.createdAt }}</h3>
      </div>
    </div>
  </div>
</template>
